version: '2'
services:
  influxdb:
    image: influxdb:1.0.0-rc1
    container_name: influxdb
    ports:
      - "8086:8086" #Influx
      - "8083:8083" #dashboard
      - "8090:8090"
    volumes:
      - ./data/influxdb:/var/lib/influxdb
